### ISSUE TITLE
mapAsync is not a function error while using

### ISSUE THREAD

**Issue by vitorsouzaalmeida** [minhna/meteor-async-migration#2]
Hello,
I'm testing the script and ai got this error:

<details>
<summary>LOGS</summary>

```bash
 ERR ../.meteor/local/bundler-cache/scanner/web.browser.legacy/reify-5a065996604b2eb9ace1f983694e85102d619fcf.js Transformation error (rootCollection.find(...).mapAsync is not a function)
TypeError: rootCollection.find(...).mapAsync is not a function
    at module.exports (/Users/vitorsouza/Desktop/work/dashboard/jscodeshift/transform.ts:288:49)
 ERR ../.meteor/local/bundler-cache/scanner/web.browser.legacy/reify-5a455a810648bbea7c617121c3ede4b9702ccb8d.js Transformation error (rootCollection.find(...).mapAsync is not a function)
TypeError: rootCollection.find(...).mapAsync is not a function
    at module.exports (/Users/vitorsouza/Desktop/work/dashboard/jscodeshift/transform.ts:288:49)
 ERR ../.meteor/local/bundler-cache/scanner/web.browser.legacy/reify-4c4ac0ddb15ed59aaa59838c3bffd05e146260c1.js Transformation error (rootCollection.find(...).mapAsync is not a function)
TypeError: rootCollection.find(...).mapAsync is not a function
    at module.exports (/Users/vitorsouza/Desktop/work/dashboard/jscodeshift/transform.ts:288:49)
 ERR ../.meteor/local/bundler-cache/scanner/web.browser.legacy/reify-4c19c517a6fd8ec50813ce189e4c1446bdc22123.js Transformation error (rootCollection.find(...).mapAsync is not a function)
TypeError: rootCollection.find(...).mapAsync is not a function
    at module.exports (/Users/vitorsouza/Desktop/work/dashboard/jscodeshift/transform.ts:288:49)
 ERR ../.meteor/local/bundler-cache/scanner/web.browser.legacy/reify-4cd9149a10e9465400ab3117102bf969a79950d7.js Transformation error (rootCollection.find(...).mapAsync is not a function)
TypeError: rootCollection.find(...).mapAsync is not a function
    at module.exports (/Users/vitorsouza/Desktop/work/dashboard/jscodeshift/transform.ts:288:49)
 ERR ../.meteor/local/bundler-cache/scanner/web.browser.legacy/reify-56ce2ff9993ebbee7eaf1022b40bee1ea3aeb716.js Transformation error (rootCollection.find(...).mapAsync is not a function)
TypeError: rootCollection.find(...).mapAsync is not a function
    at module.exports (/Users/vitorsouza/Desktop/work/dashboard/jscodeshift/transform.ts:288:49)
```

</details>

**Comment by minhna** [comment]
I think somehow you run the script against the transform file.
The original file at line 288, it's `.map()` not `.mapAsync()`
https://github.com/minhna/meteor-async-migration/blob/main/transform.ts#L288

**Comment by vitorsouzaalmeida** [comment]
@minhna I think that I know the problem.
My codebase does not declare a new collection using `new Mongo.Collection('collection')`. I need to add a case to validate it. https://github.com/minhna/meteor-async-migration/blob/24da9a13bf2c44b8b48c632bd092e95d37d69e72/utils.ts#L507-L531

**Comment by minhna** [comment]
Yes, you can modify it to make it works with your code base.
